swipe:
  3:
    left:
      shortcut: 'alt+ctrl+Right'
    right:
      shortcut: 'alt+ctrl+Left'
    up:
      shortcut: 'alt+ctrl+Down'
    down:
      shortcut: 'alt+ctrl+Up'
  4:
    left:
      shortcut: 'super+Left'
    right:
      shortcut: 'super+Right'
    up:
      shortcut: 'super+a'
    down:
      shortcut: 'super+s'
pinch:
  in:
    shortcut: 'ctrl+plus'
  out:
     shortcut: 'ctrl+minus'

threshold:
  swipe: 1
  pinch: 1

interval:
  swipe: 1
  pinch: 1
